on:
  push:
    branches: 
      - 'release-6.2'
         
env:
  RELEASE_START: 1190 # 1150, as this is latest build by GitLab CI
  CCACHE_DIR: $RUNNER_TEMP/ccache

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    container: 
      image: gustavokch/rock64build-release:latest
      credentials:
        username: gustavokch
        password: dckr_pat_HzZm-FaY8cD_h88RZoEfhWTyC9A
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Docker binary
      run: |
        apt-get -y update
        apt-get -y install docker.io
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Reset ccache statistics
      run: ccache -M 0 -F 0
    - name: Build package
      run: |
        export RELEASE=$(($RELEASE_START+$GITHUB_RUN_NUMBER))
        ./dev-make kernel-package
        
    - name: Release package
      run: |
         export GH_TOKEN="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"
         export RELEASE_START="1190"
         export RELEASE_PREFIX="$(./dev-make version)"
         export RELEASE=$(($RELEASE_START+$GITHUB_RUN_NUMBER))
         export RELEASE_NAME="$(./dev-make version)"
         export RELEASE_TITLE=($RELEASE"-release")
         export DESCRIPTION="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
         find / -type f -name "*.deb" > deb
         export DEB=$(cat deb)
         gh release create --title $RELEASE_TITLE --generate-notes -R https://github.com/gustavokch/linux-mainline-kernel $RELEASE_TITLE $DEB
